{% set name = "westpa_py3" %}
{% set version = "master" %}
{% set sha256 = "d6c3043c230e5023b85fae895c2e636320bfa061ee8e32554667333df1f7cfc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  #url: https://github.com/westpa/westpa/archive/v{{ version }}.tar.gz
  url: https://github.com/mczwier/westpa_py3/archive/{{ version }}.tar.gz
  #url: https://github.com/mczwier/westpa_py3/archive/master.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]
  ## skip: True  # [win or py3k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - cython
    - numpy 1.16.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py 2.9.*
    - pyyaml 5.1.*
    - pyzmq 18.0.*
    - matplotlib
    - blessings 1.7.*

test:
  commands:
    - "source ${PREFIX}/${PKG_NAME}-${PKG_VERSION}/westpa.sh"
    - "source ${WEST_ROOT}/bin/w_env"
    - "$WEST_PYTHON -c 'import west'"
    - "$WEST_PYTHON -c 'import west.propagators'"
    - "$WEST_PYTHON -c 'import westpa'"
    - "$WEST_PYTHON -c 'import westpa.binning'"
    - "$WEST_PYTHON -c 'import westpa.kinetics'"
    - "$WEST_PYTHON -c 'import westpa.reweight'"
    - "$WEST_PYTHON -c 'import work_managers'"
    - "$WEST_PYTHON -c 'import westtools'"
    - "$WEST_PYTHON -c 'import fasthist'"
    - "$WEST_PYTHON -c 'import mclib'"
    # Currently blocked by https://github.com/westpa/westpa/issues/70
    #- "$WEST_PYTHON -c 'import trajtree'"

about:
  home: https://westpa.github.io/westpa
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Interoperable, highly-scalable software for weighted ensemble simulation.'

  description: |
    WESTPA is a package for constructing and running stochastic simulations
    using the "weighted ensemble" approach of Huber and Kim (1996).
  doc_url: https://westpa.github.io/westpa/sphinx_index.html#tutorials
  dev_url: https://github.com/westpa

extra:
  recipe-maintainers:
    - mczwier
    - ajoshpratt
    - synapticarbors
    - burntyellow
    - ltchong
